const amenities = [
  {
    houseName: "shakkedHouse",
    list: [
      {
        imageSrc: "amenities-icons/bed.png",
        title: "beds",
        text: "threeDoubleBeds",
      },
      {
        imageSrc: "amenities-icons/bedroom.png",
        title: "bedroom",
        text: "threeBedrooms",
      },
      {
        imageSrc: "amenities-icons/sm.webp",
        title: "sm",
        text: "houndredAndFortySquaredMeters",
      },
      {
        imageSrc: "amenities-icons/appliances.webp",
        title: "appliances",
        text: "fullyEquipped",
      },
      {
        imageSrc: "amenities-icons/wifi.png",
        title: "wifi",
        text: "wifi",
      },
      {
        imageSrc: "amenities-icons/car.png",
        title: "parking",
        text: "freeParking",
      },
    ],
    fullList: [
      "air_conditioning",
      "cleaning_products",
      "dedicated_workspace",
      "dishes_and_silverware",
      "heating",
      "kitchen",
      "TV",
      "washer",
      "wifi",
      "bathtub",
      "hot_water",
      "drying_rack",
      "books_and_reading_material",
      "ethernet_connection",
      "ping_pong_table",
      "board_games",
      "childrens_books_and_toys",
      "crib",
      "ceiling_fans",
      "first_aid_kit",
      "espresso_machine",
      "dining_table",
      "dishwasher",
      "freezer",
      "hot_water",
      "kettle",
      "microwave",
      "oven",
      "refrigerator",
      "stove",
      "backyard",
      "BBQ_grill",
      "outdoor_dining_area",
      "outdoor_furniture",
      "patio_or_balcony",
      "free_parking_on_premises",
      "free_street_parking",
      "single_level_home",
    ],
  },
  {
    houseName: "avivHouse",
    list: [
      {
        imageSrc: "amenities-icons/bed.png",
        title: "beds",
        text: "threeDoubleBeds",
      },
      {
        imageSrc: "amenities-icons/bedroom.png",
        title: "bedroom",
        text: "threeBedrooms",
      },
      {
        imageSrc: "amenities-icons/sm.webp",
        title: "sm",
        text: "houndredAndTenSquaredMeters",
      },
      {
        imageSrc: "amenities-icons/appliances.webp",
        title: "appliances",
        text: "fullyEquipped",
      },
      {
        imageSrc: "amenities-icons/wifi.png",
        title: "wifi",
        text: "wifi",
      },
      {
        imageSrc: "amenities-icons/car.png",
        title: "parking",
        text: "freeParking",
      },
    ],
    fullList: [
      "air_conditioning",
      "cleaning_products",
      "dedicated_workspace",
      "dishes_and_silverware",
      "heating",
      "kitchen",
      "TV",
      "washer",
      "wifi",
      "bathtub",
      "hot_water",
      "drying_rack",
      "safe",
      "books_and_reading_material",
      "ethernet_connection",
      "ping_pong_table",
      "board_games",
      "childrens_books_and_toys",
      "crib",
      "ceiling_fans",
      "first_aid_kit",
      "espresso_machine",
      "dining_table",
      "dishwasher",
      "freezer",
      "hot_water",
      "kettle",
      "microwave",
      "oven",
      "refrigerator",
      "stove",
      "backyard",
      "BBQ_grill",
      "outdoor_dining_area",
      "outdoor_furniture",
      "patio_or_balcony",
      "free_parking_on_premises",
      "free_street_parking",
      "single_level_home",
    ],
  },
  {
    houseName: "shacharHouse",
    list: [
      {
        imageSrc: "amenities-icons/bed.png",
        title: "beds",
        text: "oneDoubleBed",
      },
      {
        imageSrc: "amenities-icons/bedroom.png",
        title: "bedroom",
        text: "twoBedrooms",
      },
      {
        imageSrc: "amenities-icons//sm.webp",
        title: "sm",
        text: "seventySquaredMeters",
      },
      {
        imageSrc: "amenities-icons/appliances.webp",
        title: "appliances",
        text: "fullyEquipped",
      },
      {
        imageSrc: "amenities-icons/wifi.png",
        title: "wifi",
        text: "wifi",
      },
      {
        imageSrc: "amenities-icons/car.png",
        title: "parking",
        text: "freeParking",
      },
    ],
    fullList: [
      "air_conditioning",
      "cleaning_products",
      "dedicated_workspace",
      "dishes_and_silverware",
      "heating",
      "kitchen",
      "TV",
      "washer",
      "wifi",
      "hot_water",
      "drying_rack",
      "books_and_reading_material",
      "ethernet_connection",
      "ping_pong_table",
      "board_games",
      "childrens_books_and_toys",
      "crib",
      "ceiling_fans",
      "first_aid_kit",
      "dining_table",
      "dishwasher",
      "freezer",
      "hot_water",
      "kettle",
      "microwave",
      "oven",
      "refrigerator",
      "stove",
      "backyard",
      "BBQ_grill",
      "outdoor_dining_area",
      "outdoor_furniture",
      "patio_or_balcony",
      "free_parking_on_premises",
      "free_street_parking",
      "single_level_home",
    ],
  },
];

export default amenities;
