export const navItems = [
  {
    id: 1,
    title: "about",
    path: "#about",
    cName: "nav-text-link about",
  },
  {
    id: 2,
    title: "typesAndSpecies",
    path: "#types-and-species",
    cName: "nav-text-link typesAndSpecies",
  },
  {
    id: 3,
    title: "information",
    path: "#information",
    cName: "nav-text-link information",
    children: [
      {
        id: 1,
        title: "whereMushroomsGrow",
        path: "/information/where-mushrooms-grow",
        cName: "submenu-item",
      },
      {
        id: 2,
        title: "TasteAndSmellInMushrooms",
        path: "/information/taste-and-smell-in-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 3,
        title: "structureAndTerms",
        path: "/information/structure-and-terms",
        cName: "submenu-item",
      },
      {
        id: 4,
        title: "whatIsMushroom",
        path: "/information/what-is-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 5,
        title: "plantMushroomBond",
        path: "/information/plant-mushroom-bond",
        cName: "submenu-item",
      },
      {
        id: 6,
        title: "hebrewNames",
        path: "/information/hebrew-names",
        cName: "submenu-item",
      },
      {
        id: 7,
        title: "inMemoryOfProfBinyamini",
        path: "/information/in-memory-of-prof-binyamini",
        cName: "submenu-item",
      },
      {
        id: 8,
        title: "whyIsItCalledAMushroom",
        path: "/information/why-is-it-called-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 9,
        title: "nutritionalValueInAMushroom",
        path: "/information/nutritional-values-in-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 10,
        title: "mushroomsAfterFire",
        path: "/information/mushrooms-after-fire",
        cName: "submenu-item",
      },
      {
        id: 11,
        title: "similarButDifferent",
        path: "/information/similar-but-different",
        cName: "submenu-item",
      },
      {
        id: 12,
        title: "photographingMushrooms",
        path: "/information/photographing-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 13,
        title: "mushroomsCounting",
        path: "/information/mushrooms-counting",
        cName: "submenu-item",
      },
      {
        id: 14,
        title: "eatingMushrooms",
        path: "/information/eating-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 15,
        title: "successionInMushrooms",
        path: "/information/succession-in-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 16,
        title: "foodAndMedicine",
        path: "/information/food-and-medicine",
        cName: "submenu-item",
      },
      {
        id: 17,
        title: "taxonomy",
        path: "/information/taxonomy",
        cName: "submenu-item",
      },
      {
        id: 18,
        title: "radioactivity",
        path: "/information/radioactivity",
        cName: "submenu-item",
      },
    ],
  },
  {
    id: 4,
    title: "observations",
    path: "#observations",
    cName: "nav-text-link observations",
    children: [
      {
        id: 1,
        title: "binyaminaMeddow",
        path: "/observations/binyamina-meddow",
        cName: "submenu-item",
      },
      {
        id: 2,
        title: "sharonShfela",
        path: "/observations/sharon-shfela",
        cName: "submenu-item",
      },
      {
        id: 3,
        title: "mushroomsInOdemForest",
        path: "/observations/mushrooms-in-odem-forest",
        cName: "submenu-item",
      },
      {
        id: 4,
        title: "mushroomsInTheGilboa",
        path: "/observations/mushrooms-in-the-gilboa",
        cName: "submenu-item",
      },
      {
        id: 5,
        title: "mushroomsInTheCarmel",
        path: "/observations/mushrooms-in-the-carmel",
        cName: "submenu-item",
      },
      {
        id: 6,
        title: "mushroomsInWestGalil",
        path: "/observations/mushrooms-in-west-galil",
        cName: "submenu-item",
      },
      {
        id: 7,
        title: "yehudaAndModiin",
        path: "/observations/yehuda-and-modiin",
        cName: "submenu-item",
      },
      {
        id: 8,
        title: "menasheMountains",
        path: "/observations/menashe-mountains",
        cName: "submenu-item",
      },
      {
        id: 9,
        title: "shomron",
        path: "/observations/shomron",
        cName: "submenu-item",
      },
    ],
  },
  {
    id: 5,
    title: "folklore",
    path: "#folklore",
    cName: "nav-text-link folklore",
  },
  {
    id: 6,
    title: "literature",
    path: "#literature",
    cName: "nav-text-link literature",
  },
  {
    id: 7,
    title: "gallery",
    path: "#gallery",
    cName: "nav-text-link gallery",
  },
];
