export const navItems = [
  {
    id: 1,
    title: "aboutLink",
    path: "#about",
    cName: "nav-text-link",
  },
  {
    id: 2,
    title: "galleryLink",
    path: "#gallery",
    cName: "nav-text-link",
  },
  {
    id: 3,
    title: "folkloreLink",
    path: "#folklore",
    cName: "nav-text-link",
  },
  {
    id: 4,
    title: "informationLink",
    path: "#information",
    cName: "nav-text-link",
    children: [
      {
        id: 1,
        title: "whereMushroomsGrow",
        path: "/information/where-mushrooms-grow",
        cName: "submenu-item",
      },
      {
        id: 2,
        title: "TasteAndSmellInMushrooms",
        path: "/information/taste-and-smell-in-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 3,
        title: "structureAndTerms",
        path: "/information/structure-and-terms",
        cName: "submenu-item",
      },
      {
        id: 4,
        title: "whatIsMushroom",
        path: "/information/what-is-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 5,
        title: "tripToSwitzerland",
        path: "/information/trip-to-switzerland",
        cName: "submenu-item",
      },
      {
        id: 6,
        title: "plantMushroomBond",
        path: "/information/plant-mushroom-bond",
        cName: "submenu-item",
      },
      {
        id: 7,
        title: "hebrewNames",
        path: "/information/hebrew-names",
        cName: "submenu-item",
      },
      {
        id: 8,
        title: "inMemoryOfProfBinyamini",
        path: "/information/in-memory-of-prof-binyamini",
        cName: "submenu-item",
      },
      {
        id: 9,
        title: "whyIsItCalledAMushroom",
        path: "/information/why-is-it-called-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 10,
        title: "nutritionalValueInAMushroom",
        path: "/information/nutritional-values-in-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 11,
        title: "nutritionalValueInAMushroom",
        path: "/information/nutritional-values-in-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 12,
        title: "italyConference",
        path: "/information/italy-conference",
        cName: "submenu-item",
      },
    ],
  },
];
