export const navItems = [
  {
    id: 1,
    title: "aboutLink",
    path: "#about",
    cName: "nav-text-link",
  },
  {
    id: 2,
    title: "galleryLink",
    path: "#gallery",
    cName: "nav-text-link",
  },
  {
    id: 3,
    title: "folkloreLink",
    path: "#folklore",
    cName: "nav-text-link",
  },
  {
    id: 4,
    title: "informationLink",
    path: "#information",
    cName: "nav-text-link",
    children: [
      {
        id: 1,
        title: "whereMushroomsGrow",
        path: "/information/where-mushrooms-grow",
        cName: "submenu-item",
      },
      {
        id: 2,
        title: "TasteAndSmellInMushrooms",
        path: "/information/taste-and-smell-in-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 3,
        title: "structureAndTerms",
        path: "/information/structure-and-terms",
        cName: "submenu-item",
      },
      {
        id: 4,
        title: "whatIsMushroom",
        path: "/information/what-is-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 5,
        title: "plantMushroomBond",
        path: "/information/plant-mushroom-bond",
        cName: "submenu-item",
      },
      {
        id: 6,
        title: "hebrewNames",
        path: "/information/hebrew-names",
        cName: "submenu-item",
      },
      {
        id: 7,
        title: "inMemoryOfProfBinyamini",
        path: "/information/in-memory-of-prof-binyamini",
        cName: "submenu-item",
      },
      {
        id: 8,
        title: "whyIsItCalledAMushroom",
        path: "/information/why-is-it-called-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 9,
        title: "nutritionalValueInAMushroom",
        path: "/information/nutritional-values-in-a-mushroom",
        cName: "submenu-item",
      },
      {
        id: 10,
        title: "mushroomsAfterFire",
        path: "/information/mushrooms-after-fire",
        cName: "submenu-item",
      },
      {
        id: 11,
        title: "similarButDifferent",
        path: "/information/similar-but-different",
        cName: "submenu-item",
      },
      {
        id: 12,
        title: "photographingMushrooms",
        path: "/information/photographing-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 13,
        title: "mushroomsCounting",
        path: "/information/mushrooms-counting",
        cName: "submenu-item",
      },
      {
        id: 14,
        title: "eatingMushrooms",
        path: "/information/eating-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 15,
        title: "successionInMushrooms",
        path: "/information/succession-in-mushrooms",
        cName: "submenu-item",
      },
      {
        id: 16,
        title: "foodAndMedicine",
        path: "/information/food-and-medicine",
        cName: "submenu-item",
      },
      {
        id: 17,
        title: "taxonomy",
        path: "/information/taxonomy",
        cName: "submenu-item",
      },
      {
        id: 18,
        title: "radioactivity",
        path: "/information/radioactivity",
        cName: "submenu-item",
      },
    ],
  },
  {
    id: 5,
    title: "typesAndSpecies",
    path: "#typesAndSpecies",
    cName: "nav-text-link",
  },
  {
    id: 6,
    title: "toursAndConferences",
    path: "#toursAndConferences",
    cName: "nav-text-link",
    children: [
      {
        id: 1,
        title: "tripToSwitzerland",
        path: "/tours-and-conferences/trip-to-switzerland",
        cName: "submenu-item",
      },
      {
        id: 2,
        title: "italyConference",
        path: "/tours-and-conferences/italy-conference",
        cName: "submenu-item",
      },
      {
        id: 3,
        title: "mushroomsInOdemForest",
        path: "/tours-and-conferences/mushrooms-in-odem-forest",
        cName: "submenu-item",
      },
      {
        id: 4,
        title: "studyTourToCyprus",
        path: "/tours-and-conferences/study-tour-to-cyprus",
        cName: "submenu-item",
      },
      {
        id: 5,
        title: "mushroomsInTheGilboa",
        path: "/tours-and-conferences/mushrooms-in-the-gilboa",
        cName: "submenu-item",
      },
    ],
  },
  {
    id: 7,
    title: "literture",
    path: "#literture",
    cName: "nav-text-link",
  },
  {
    id: 8,
    title: "observations",
    path: "#observations",
    cName: "nav-text-link",
    children: [
      {
        id: 1,
        title: "sharonShfela",
        path: "/tours-and-conferences/sharon-shfela",
        cName: "submenu-item",
      },
    ],
  },
];
